foreground #cad3f5
background #24273a
selection_foreground #24273a
selection_background #89b4fa
cursor #89b4fa
cursor_text_color #24273a
url_color #89b4fa
active_border_color #89b4fa
inactive_border_color #494d64
