foreground              #f0f2f5
background              #22262b
selection_foreground    #08090a
selection_background    #d9cb9e

cursor                  #8fa3b8
cursor_text_color       #08090a

url_color               #a2b5cd

active_border_color     #8fa3b8
inactive_border_color   #32373e
bell_border_color       #d98880

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #08090a
active_tab_background   #73889c
inactive_tab_foreground #b3b9c2
inactive_tab_background #22262b
tab_bar_background      #08090a

mark1_foreground #08090a
mark1_background #8fa3b8
mark2_foreground #08090a
mark2_background #9bbd9e
mark3_foreground #08090a
mark3_background #a2b5cd

color0 #32373e
color8 #cfd4db

color1 #d98880
color9 #bf6b63

color2  #8fa3b8
color10 #73889c

color3  #a2b5cd
color11 #d4b2bd

color4  #9bbd9e
color12 #d9cb9e

color5  #73889c
color13 #b0a8b8

color6  #d9cb9e
color14 #d4b2bd

color7  #b3b9c2
color15 #f0f2f5
