[bar.default]
start = ["arch", "launcher", "wallpaper", "workspaces"]

[widget.arch]
type    = "custom_button"
custom_image = "/home/fractu/.config/noctalia/icons/arch.svg"
custom_image_colorize = true
tooltip = "Centro de control"

[widget.arch.actions]
left = "panel-toggle control-center"
