[theme]
mode            = "dark"
source          = "custom"
custom_palette  = "BlancoGris"
pure_black_dark = false

[theme.templates]
enable_builtin_templates = true
builtin_ids              = ["kitty"]
