source = hyprlock-colors.conf

general {
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 6
    brightness = 0.6
}

# hora (horas arriba, minutos abajo)
label {
    monitor =
    text = cmd[update:1000] echo "$(date +%H)"
    color = $text
    font_size = 130
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, 300
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +%M)"
    color = $accent
    font_size = 130
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, 170
    halign = center
    valign = center
}

# fecha
label {
    monitor =
    text = cmd[update:60000] echo "$(date +'%A, %d %B')"
    color = $muted
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, 70
    halign = center
    valign = center
}

# imagen (logo o avatar)
image {
    monitor =
    path = ~/Descargas/icon.jpg
    size = 100
    rounding = -1
    border_size = 2
    border_color = $accent
    position = 0, -30
    halign = center
    valign = center
}

# usuario
label {
    monitor =
    text = $USER
    color = $text
    font_size = 16
    font_family = JetBrainsMono Nerd Font
    position = 0, -110
    halign = center
    valign = center
}

# contraseña
input-field {
    monitor =
    size = 280, 50
    rounding = 25
    outline_thickness = 2
    outer_color = $accent
    inner_color = $inner
    font_color = $text
    check_color = $ok
    fail_color = $fail
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true
    fade_on_empty = false
    placeholder_text = Contraseña
    fail_text = Incorrecta
    position = 0, -180
    halign = center
    valign = center
}
